kind: pipeline
name: default

steps:
  - name: build
    image: node:12.6
    commands:
      - npm install
      - npm run build
      - mkdir /drone/src/docs
      - mv ./build/* /drone/src/docs
      - git remote -v
      - git remote set-url origin https://github.com/alcbotta/commit_convention.git
      - git remote -v
  - name: publish
    image: plugins/gh-pages
    settings:
      username:
        from_secret: github_username
      password:
        from_secret: github_password
