kind: pipeline
name: default

steps:
  - name: build
    image: node:12.6
    commands:
      - npm install
      - npm run build
      - mkdir /drone/src/docs
      - mv ./build/* /drone/src/docs
      - git remote set-url origin https://github.com/alcbotta/commit_convention.git
      - git config --global user.email "alcbotta@gmail.com"
      - git config --global user.email "alcbotta"
  - name: publish
    image: plugins/gh-pages
    commands:
      - cat ~/.gitconfig
    settings:
      remote_url: https://github.com/alcbotta/commit_convention.git
      username:
        from_secret: github_username
      password:
        from_secret: github_password
