kind: pipeline
name: default

steps:
- name: build
  image: node:12.6
  commands: 
    - npm install
    - npm run build
    - mv ./build/* /drone/src/public
    - git config --global user.email "alcbotta"
    - git config --global user.name "Andre Botta"
- name: publish  
  image: plugins/gh-pages
  settings:
    PLUGIN_USER_NAME: "alcbotta"
    PLUGIN_USER_EMAIL: "alcbotta@gmail.com"
    username:
      from_secret: github_username
    password:
      from_secret: github_password
    pages_directory: public/
    temporary_base: tmp/